library(tm)
set.seed(5678)
USblogs_sub <- sample(USblogs, length(USblogs)*0.5)
USnews_sub <- sample(USnews, length(USnews)*0.5)
UStwitter_sub <- sample(UStwitter, length(UStwitter)*0.5)
total_set <- c(USblogs_sub, USnews_sub, UStwitter_sub)

corpus <- Corpus(VectorSource(total_set))
corpus <- tm_map(corpus, stripWhitespace)
corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeWords, stopwords("english"))